CREATE TABLE IF NOT EXISTS admin_users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  phone TEXT NOT NULL DEFAULT '7358266257',
  email TEXT NOT NULL DEFAULT 'info@skbuilders.com',
  facebook TEXT DEFAULT 'https://facebook.com',
  instagram TEXT DEFAULT 'https://instagram.com',
  whatsapp TEXT DEFAULT '7358266257',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS site_settings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  company_name TEXT NOT NULL DEFAULT 'SK BUILDERS',
  company_subtitle TEXT NOT NULL DEFAULT '& PROPERTY CONSULTANT',
  phone TEXT NOT NULL DEFAULT '7358266257',
  email TEXT NOT NULL DEFAULT 'info@skbuilders.com',
  location TEXT NOT NULL DEFAULT 'Poonamallee, Mangadu, Kundrathur, Tamil Nadu - 600056',
  service_areas TEXT NOT NULL DEFAULT 'Poonamallee • Mangadu • Kundrathur',
  hero_tagline TEXT NOT NULL DEFAULT 'BUILDING QUALITY HOMES.',
  hero_headline_find TEXT NOT NULL DEFAULT 'Find',
  hero_headline_property TEXT NOT NULL DEFAULT 'Right Property',
  hero_headline_confidence TEXT NOT NULL DEFAULT 'Confidence',
  hero_subtitle TEXT NOT NULL DEFAULT 'We build individual houses, offer residential land plots, execute contract house construction, and provide expert property consultation in Poonamallee, Mangadu & Kundrathur.',
  facebook_url TEXT DEFAULT 'https://facebook.com',
  instagram_url TEXT DEFAULT 'https://instagram.com',
  whatsapp_number TEXT DEFAULT '7358266257',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS services (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  icon_name TEXT NOT NULL DEFAULT 'Home',
  link_url TEXT NOT NULL DEFAULT '#properties',
  display_order INTEGER DEFAULT 1
);

-- 1. PROPERTIES TABLE (Houses / Buildings)
CREATE TABLE IF NOT EXISTS properties (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  property_id TEXT,
  title TEXT NOT NULL,
  type TEXT NOT NULL,
  listing_type TEXT NOT NULL DEFAULT 'For Sale',
  status TEXT NOT NULL DEFAULT 'Available',
  address TEXT,
  area TEXT,
  city TEXT DEFAULT 'Chennai',
  pincode TEXT,
  maps_url TEXT,
  latitude TEXT,
  longitude TEXT,
  landmark TEXT,
  price TEXT NOT NULL,
  price_display_type TEXT DEFAULT 'Exact Price',
  negotiable TEXT DEFAULT 'Yes',
  price_per_sqft TEXT,
  plot_area TEXT,
  plot_size TEXT,
  plot_area_unit TEXT DEFAULT 'sq.ft',
  builtup_area TEXT,
  builtup_area_unit TEXT DEFAULT 'sq.ft',
  floor_area TEXT,
  floors TEXT,
  bedrooms TEXT,
  bathrooms TEXT,
  balconies TEXT,
  kitchens TEXT,
  living_room TEXT,
  dining_area TEXT,
  pooja_room TEXT,
  construction_status TEXT DEFAULT 'Completed',
  year_built TEXT,
  construction_type TEXT DEFAULT 'RCC / Concrete',
  roof_type TEXT DEFAULT 'RCC Flat Concrete Roof',
  parking_available TEXT DEFAULT 'Yes',
  parking_type TEXT DEFAULT 'Car + Bike',
  cars TEXT,
  bikes TEXT,
  compound_wall INTEGER DEFAULT 0,
  gate INTEGER DEFAULT 0,
  water_connection INTEGER DEFAULT 0,
  eb_connection INTEGER DEFAULT 0,
  sewer_connection INTEGER DEFAULT 0,
  borewell INTEGER DEFAULT 0,
  overhead_tank INTEGER DEFAULT 0,
  ground_water INTEGER DEFAULT 0,
  road_access INTEGER DEFAULT 0,
  facing TEXT DEFAULT 'East',
  road_width TEXT,
  road_width_unit TEXT DEFAULT 'ft',
  road_type TEXT,
  corner_property TEXT DEFAULT 'No',
  patta_status TEXT DEFAULT 'Not Provided',
  ec_status TEXT DEFAULT 'Not Provided',
  approved_plan_status TEXT DEFAULT 'Not Provided',
  building_approval_status TEXT DEFAULT 'Not Provided',
  property_tax_status TEXT DEFAULT 'Not Provided',
  sale_deed_status TEXT DEFAULT 'Not Provided',
  other_documents TEXT,
  short_description TEXT,
  full_description TEXT,
  highlights TEXT,
  published INTEGER DEFAULT 1,
  featured INTEGER DEFAULT 0,
  category TEXT DEFAULT 'Houses for Sale',
  location TEXT,
  image TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- PROPERTY IMAGES TABLE
CREATE TABLE IF NOT EXISTS property_images (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  property_id INTEGER NOT NULL,
  image_url TEXT NOT NULL,
  caption TEXT,
  sort_order INTEGER DEFAULT 0,
  is_cover INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 2. LAND TABLE (Residential Plots / Land)
CREATE TABLE IF NOT EXISTS land (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  land_id TEXT,
  title TEXT NOT NULL,
  land_type TEXT NOT NULL DEFAULT 'Residential Plot',
  listing_type TEXT NOT NULL DEFAULT 'For Sale',
  status TEXT NOT NULL DEFAULT 'Available',
  address TEXT,
  area TEXT,
  city TEXT DEFAULT 'Chennai',
  pincode TEXT,
  maps_url TEXT,
  latitude TEXT,
  longitude TEXT,
  landmark TEXT,
  plot_area TEXT NOT NULL,
  plot_area_unit TEXT DEFAULT 'sq.ft',
  frontage TEXT,
  length TEXT,
  width TEXT,
  total_price TEXT NOT NULL,
  price_per_sqft TEXT,
  negotiable TEXT DEFAULT 'Yes',
  price_display_type TEXT DEFAULT 'Exact Price',
  approval_status TEXT DEFAULT 'Not Provided',
  facing TEXT DEFAULT 'East',
  road_width TEXT,
  road_width_unit TEXT DEFAULT 'ft',
  road_type TEXT,
  road_facing TEXT,
  corner_plot TEXT DEFAULT 'No',
  eb_available INTEGER DEFAULT 0,
  water_available INTEGER DEFAULT 0,
  drainage_available INTEGER DEFAULT 0,
  borewell_available INTEGER DEFAULT 0,
  patta_status TEXT DEFAULT 'Not Provided',
  ec_status TEXT DEFAULT 'Not Provided',
  parent_documents_status TEXT DEFAULT 'Not Provided',
  sale_deed_status TEXT DEFAULT 'Not Provided',
  approval_documents_status TEXT DEFAULT 'Not Provided',
  other_documents TEXT,
  nearby_school TEXT,
  nearby_hospital TEXT,
  nearby_bus_stop TEXT,
  nearby_railway TEXT,
  nearby_main_road TEXT,
  nearby_shopping TEXT,
  short_description TEXT,
  full_description TEXT,
  highlights TEXT,
  published INTEGER DEFAULT 1,
  featured INTEGER DEFAULT 0,
  location TEXT,
  image TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- LAND IMAGES TABLE
CREATE TABLE IF NOT EXISTS land_images (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  land_id INTEGER NOT NULL,
  image_url TEXT NOT NULL,
  caption TEXT,
  sort_order INTEGER DEFAULT 0,
  is_cover INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 3. PROJECTS TABLE (Construction Projects)
CREATE TABLE IF NOT EXISTS projects (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id TEXT,
  name TEXT,
  title TEXT NOT NULL,
  project_type TEXT DEFAULT 'Individual House',
  status TEXT NOT NULL DEFAULT 'Completed',
  address TEXT,
  area TEXT,
  city TEXT DEFAULT 'Chennai',
  pincode TEXT,
  maps_url TEXT,
  latitude TEXT,
  longitude TEXT,
  plot_area TEXT,
  plot_area_unit TEXT DEFAULT 'sq.ft',
  builtup_area TEXT,
  builtup_area_unit TEXT DEFAULT 'sq.ft',
  floors TEXT,
  bedrooms TEXT,
  bathrooms TEXT,
  start_date TEXT,
  expected_completion_date TEXT,
  actual_completion_date TEXT,
  rcc_structure INTEGER DEFAULT 0,
  concrete_roof INTEGER DEFAULT 0,
  compound_wall INTEGER DEFAULT 0,
  gate INTEGER DEFAULT 0,
  parking INTEGER DEFAULT 0,
  water_connection INTEGER DEFAULT 0,
  electrical_work INTEGER DEFAULT 0,
  plumbing INTEGER DEFAULT 0,
  painting INTEGER DEFAULT 0,
  interior_work INTEGER DEFAULT 0,
  overview TEXT,
  description TEXT,
  construction_details TEXT,
  special_features TEXT,
  challenges TEXT,
  solutions TEXT,
  client_requirements TEXT,
  final_outcome TEXT,
  completion_date TEXT,
  cover_image TEXT NOT NULL,
  published INTEGER DEFAULT 1,
  featured INTEGER DEFAULT 0,
  location TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- PROJECT IMAGES TABLE
CREATE TABLE IF NOT EXISTS project_images (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER NOT NULL,
  image_url TEXT NOT NULL,
  category TEXT DEFAULT 'completed',
  caption TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS gallery (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  image TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS testimonials (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  client_name TEXT NOT NULL,
  location TEXT NOT NULL,
  quote TEXT NOT NULL,
  rating INTEGER DEFAULT 5,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS leads (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT,
  service TEXT,
  property_id TEXT,
  message TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS media_videos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  filename TEXT NOT NULL,
  filepath TEXT NOT NULL,
  video_type TEXT DEFAULT 'hero',
  is_primary INTEGER DEFAULT 0,
  file_size INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
